import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css'

import Banner from '../components/Banner';

const handleOnBannerButtonClick = () => {
  console.log('hi')
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerButtonClick} />
      </main>
    </div>
  )
}

export default Home
